### ISSUE TITLE
`create-rediagram-project ` is not work

### ISSUE THREAD

**Issue by yamatatsu** [kamiazya/rediagram#199]
**Describe the bug**
I tried `yarn start` and following error is occurred.

```
src/MyInfra.rediagram.tsx
(node:24669) UnhandledPromiseRejectionWarning: Error: spawn dot ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**To Reproduce**

```sh
> yarn create rediagram-project my-rediagram
> yarn start
```

**Expected behavior**
Success `yarn start`, without errors.

**Screenshots**

 - OS: [macos catalina 10.15.7]
 - Node.js version [14.x]
 - Package Name
     - create-rediagram-project
 - Package Version
     - latest

**Additional context**

I tried to catch error. Result is following;

```

Error: spawn dot ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn dot',
  path: 'dot',
  spawnargs: [
    '-Tpng',
    '-o',
    '/my/project/dir/my-rediagram/img/MyInfra.rediagram.png',
    '/var/folders/fr/5qmpnmcs41v1ypvgv454y6c40000gq/T/tmp-27783-vtNDIm2O94H7'
  ],
  cmd: 'dot -Tpng -o /my/project/dir/my-rediagram/img/MyInfra.rediagram.png /var/folders/fr/5qmpnmcs41v1ypvgv454y6c40000gq/T/tmp-27783-vtNDIm2O94H7',
  stdout: <Buffer >,
  stderr: <Buffer >
}
```

This is occurred at here https://github.com/ts-graphviz/node/blob/master/src/executeDot.ts#L25 , i think.

I don't remove `./my-rediagram/img` folder.

`tmp-promise` has something wrong?

thanks.

**Comment by yamatatsu** [comment]
This has resolved...
`brew install graphviz`

sorry..
