### ISSUE TITLE
the Browser image vanishes

### ISSUE THREAD

**Issue by odd12258053** [kamiazya/rediagram#97]
I caught the below error.
```
$ git clone https://github.com/kamiazya/rediagram.git
$ cd rediagram/docker

// I wrote a model that same as the example in README.md.
$ vim MyInfra.rediagram.tsx
$ make build
...
$ docker run --rm -v `pwd`:/workdir/ rediagram:0.1.1
(node:1) UnhandledPromiseRejectionWarning: Error: Command failed: dot -Tpng -o MyInfra.rediagram.png
Warning: No such file or directory while opening /node_modules/@rediagram/aws/assets/general/Client.png
Error: No or improper image file="/node_modules/@rediagram/aws/assets/general/Client.png"
in label of node Browser
Warning: Arrow type "point" unknown - ignoring

    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at Object.renderDot (/node_modules/@ts-graphviz/node/lib/index.js:51:15)
    at renderToFile (/node_modules/rediagram/lib/render.js:13:12)
    at render (/node_modules/rediagram/lib/render.js:17:5)
    at Object.PNG (/node_modules/rediagram/lib/render.js:27:5)
    at Object.<anonymous> (/workdir/MyInfra.rediagram.tsx:5:1)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Module.m._compile (/usr/local/share/.config/yarn/global/node_modules/ts-node/src/index.ts:1043:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by odd12258053** [comment]
Sorry, I found an expected image.

**Comment by kamiazya** [comment]
@odd12258053 

It seems that the image included in the `@rediagram/aws` package was unintentionally missing in versions 0.2.0 and later.

I'll fix it to include the missing image in an upcoming release.

**Comment by kamiazya** [comment]
@odd12258053 

Sorry, the `AWSGeneralIcon` component mentioned in the README has been migrated to the GeneralIcon` in the rediagram package.

Since the README has been updated, if you execute it again, an image will be output, so please try it.

**Comment by odd12258053** [comment]
@kamiazya
Thank you, I tried it and to export an expected image.
